# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
# The code goes here
import numpy as np

In [1]:
sum.a

AttributeError: 'builtin_function_or_method' object has no attribute 'a'

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [63]:
#Code comes here
arr1 = np.tile(1, 10)
print(arr1)

arr2 = np.arange(1, 20, 1, dtype="int")
print(arr2)

arr3 = np.ones((5, 5), dtype="int")
print(arr3)

#it did do that but this is a better way
print(np.ones(10))
print(np.array(range(21)))
print(np.ones((5, 5), dtype=int))

[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [68]:
# Code comes here
arr4 = np.random.rand(3, 3, 3)
print(arr4)
arr4.reshape(27)

# answer 
x = np.random.randn(3, 3, 3)
x
x.reshape(-1) # or x.reshape(27)


[[[0.11347015 0.77970322 0.87775181]
  [0.40510577 0.01212719 0.30794582]
  [0.98626156 0.33191926 0.042651  ]]

 [[0.49885529 0.92709635 0.67781384]
  [0.84812517 0.8379069  0.83480379]
  [0.70578484 0.08795606 0.48942555]]

 [[0.10984822 0.32884498 0.13908524]
  [0.47021734 0.9588442  0.56224577]
  [0.07858118 0.42776316 0.22919972]]]


array([-0.69675074,  0.27315974, -0.04292963,  0.69083594,  0.18933633,
       -0.04330975, -0.18327444,  0.54906037,  0.49994996,  0.78948504,
        0.04472939,  0.23282667,  0.3901983 , -0.27926379,  0.81870749,
       -0.46026019,  0.49619734, -1.42431159,  0.22171852,  0.19491771,
       -0.62252209,  0.25488017,  0.26413893,  1.54522769,  2.66711861,
        0.54827296, -0.71433347])

# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [72]:
# Code comes here
arr5 = np.random.randint(1,10,20)
print(arr5)

#answer:

np.linspace(1, 10, 20)


[7 5 8 9 7 9 3 7 7 2 1 1 8 2 2 8 4 7 1 6]


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [75]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
20

20

In [76]:
#Code goes here
a[3,4]

20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [77]:
a[1:,3:]


array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [78]:
a[1,:]


array([ 6,  7,  8,  9, 10])

## 2.5 

Calculate the sum of all the numbers in `a`.

In [95]:
# Code comes here

sum(a)

array([55, 60, 65, 70, 75])

## 2.6 

Calculate the sum of each row in `a`.

In [83]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [96]:
a[a > a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [49]:
# Codes comes here
import numpy as np
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [52]:
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"
df = pd.read_csv(url)
df

country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]

In [ ]:
## 2.10 

How many rows and columns are there in the dataframe?

In [53]:
df.shape

(1430, 4)

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [56]:
df["co2_emmission"].mean()


74.383993006993

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [58]:
df.iloc[df['co2_emmission'].idxmax()]

country          Argentina
food_category         Beef
consumption          55.48
co2_emmission       1712.0
Name: 2, dtype: object

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [59]:
df.query("co2_emmission > 1000")

country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94

## 2.14

Which country consumes the least amount of beef per person per year?


In [60]:
(df.query("food_category == 'Beef'")
    .sort_values(by="consumption")
     .head(1))

country food_category  consumption  co2_emmission
1410  Liberia          Beef         0.78          24.07

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [61]:
meat = ['Poultry', 'Pork', 'Fish', 'Lamb & Goat', 'Beef']
df["co2_emmission"][df['food_category'].isin(meat)].sum()

74441.13

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [62]:
meat = ['Poultry', 'Pork', 'Fish', 'Lamb & Goat', 'Beef']
df["co2_emmission"][~df['food_category'].isin(meat)].sum() #check the use of ~

31927.98

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.